# Generated by Django 3.1.7 on 2021-03-01 22:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mainsite', '0005_picture_likes'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Like',
        ),
    ]
