# Generated by Django 3.1.7 on 2021-03-01 23:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainsite', '0006_delete_like'),
    ]

    operations = [
        migrations.AlterField(
            model_name='friendrequest',
            name='accepted',
            field=models.BooleanField(blank=True),
        ),
    ]
