# Generated by Django 3.1.7 on 2021-03-01 23:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainsite', '0007_auto_20210302_0127'),
    ]

    operations = [
        migrations.AlterField(
            model_name='friendrequest',
            name='accepted',
            field=models.BooleanField(blank=True, default=False),
        ),
    ]
