# Generated by Django 3.1.7 on 2021-03-04 15:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainsite', '0010_like'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='picture',
            name='likes',
        ),
        migrations.AddField(
            model_name='like',
            name='time',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
