# Generated by Django 3.1.7 on 2021-03-04 15:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainsite', '0011_auto_20210304_1736'),
    ]

    operations = [
        migrations.AddField(
            model_name='friendrequest',
            name='time',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
