# Generated by Django 3.1.7 on 2021-03-16 02:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainsite', '0018_userauth'),
    ]

    operations = [
        migrations.CreateModel(
            name='TwoFactorAuthMsg',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hash_url', models.CharField(max_length=1000)),
                ('two_factor_code', models.IntegerField()),
            ],
        ),
    ]
