# Generated by Django 3.1.7 on 2021-03-15 17:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='chatroom',
            name='last_msg_time',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
