# Generated by Django 3.1.7 on 2021-04-03 23:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('async_chat', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='postmessage',
            name='post_image',
            field=models.CharField(max_length=1000),
        ),
    ]
