# Generated by Django 3.1.7 on 2021-03-17 21:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('async_chat', '0002_message_chatroom'),
    ]

    operations = [
        migrations.AddField(
            model_name='chatroom',
            name='last_msg_time',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
