# Generated by Django 3.1.7 on 2021-04-04 23:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('async_chat', '0003_auto_20210404_0230'),
    ]

    operations = [
        migrations.AddField(
            model_name='message',
            name='datetimestamp',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='postmessage',
            name='datetimestamp',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
